import type { Metadata } from "next";
import { Quando, Great_Vibes } from "next/font/google";
import "./globals.css";

const quando = Quando({
  variable: "--font-quando",
  subsets: ["latin"],
  weight: "400"
});

const great_Vibes = Great_Vibes({
  variable: "--font-great-vibes",
  subsets: ["latin"],
  weight: "400"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${quando.variable} ${great_Vibes.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
